<a href="https://colab.research.google.com/github/gayaniindunil/facegeneration_GAN/blob/master/simple_image_generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#this program is created to generate face images using a unconditional GAN.
#USED IMAGE DATASET  -> Person images from Natural Images dataset
#number of images -> 986 images
#original image size -> 256 X 265

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
#papers : 
# 1.https://arxiv.org/pdf/1511.06434.pdf%C3%AF%C2%BC%E2%80%B0%C3%A3%E2%82%AC%E2%80%98
# 2. 

#Refered github repositories : 
# 1. art-DCGAN : https://github.com/robbiebarrat/art-DCGAN
# 2. https://github.com/mitchelljy/DCGAN-Keras/blob/master/DCGAN.py

In [0]:
from keras.models import Sequential, Model, load_model
from keras.layers import UpSampling2D, Conv2D, Activation, BatchNormalization, Reshape, Dense, Input, LeakyReLU, Dropout, Flatten, ZeroPadding2D
from keras.optimizers import Adam
from keras.preprocessing import image
import numpy as np
from PIL import Image
import os
import glob
# from scipy.misc import *
import imageio

Using TensorFlow backend.


In [0]:
root_dir = "/content/drive/My Drive/Colab_Notebooks/image_generation"


Mounted at /content/drive


In [0]:
# model parameters
data_dir = root_dir + '/datasets/person/*.jpg'

output_save_dir = root_dir + '/Explore_GANs/DCGAN/output'
model_save_name = 'DCGAN.h5'

save_path = output_save_dir + "/models"
discriminator_path = save_path + "/discrim.h5"
generator_path = save_path + "/generat.h5"
output_img_save_dir = root_dir + '/Explore_GANs/DCGAN/output_imgs'

output_directory = output_img_save_dir

In [0]:
#hyper parameters
img_size = (256, 256)
channels = 3
kernel_size = 3
upsample_layers = 5
starting_filters = 64

In [0]:
def load_imgs1(data_dir):
  images = os.listdir(data_dir)

  for img_path in images:
    img = Image.open(data_dir + '/' + img_path)
    
    w,h = img.size
    rescale_ratio = 256 / min(w,h)
    img = img.resize((int(rescale_ratio*w),int(rescale_ratio*h)), Image.LANCZOS)
    # display(img)

In [0]:
def load_imgs(image_path):
  X_train = []
  for i in glob.glob(image_path):
    img = Image.open(i)
    img = img.resize((256,256))
    img = np.array(img)
    X_train.append(img)
  
  X_train = np.array(X_train)
  return  X_train


In [0]:
x = [659, 976,  16, 119, 721, 148]

imgs = []
for img in x:
  i = (a[img])
  w,h = i.shape[0:2]
  print(w,h)
#   rescale_ratio = 256 / min(w,h)
#   img = i.resize((int(rescale_ratio*w),int(rescale_ratio*h)), Image.LANCZOS)
#   # display(img)
#   # Rescale images from -1 to 1
#   i = (i.astype(np.float32) - 127.5) / 127.5
#   display(i)
#   imgs.append(i)
# imgs = np.array(imgs)

NameError: ignored

In [0]:
def build_generator():
  noise_shape = (100,)

  # This block of code can be a little daunting, but essentially it automatically calculates the required starting
  # array size that will be correctly upscaled to our desired image size.
  #
  # We have 5 Upsample2D layers which each double the images width and height, so we can determine the starting
  # x size by taking (x / 2^upsample_count) So for our target image size, 256x192, we do the following:
  # x = (192 / 2^5), y = (256 / 2^5) [x and y are reversed within the model]
  # We also need a 3rd dimension which is chosen relatively arbitrarily, in this case it's 64.
  model = Sequential()
  model.add(Dense(starting_filters * (img_size[0] // (2 ** upsample_layers))  *  (img_size[1] // (2 ** upsample_layers)),
            activation="relu", input_shape=noise_shape))
  model.add(Reshape(((img_size[0] // (2 ** upsample_layers)),
                      (img_size[1] // (2 ** upsample_layers)),
                      starting_filters)))
  model.add(BatchNormalization(momentum=0.8))

  model.add(UpSampling2D())  # 6x8 -> 12x16
  model.add(Conv2D(1024, kernel_size=kernel_size, padding="same"))
  model.add(Activation("relu"))
  model.add(BatchNormalization(momentum=0.8))

  model.add(UpSampling2D())  # 12x16 -> 24x32
  model.add(Conv2D(512, kernel_size=kernel_size, padding="same"))
  model.add(Activation("relu"))
  model.add(BatchNormalization(momentum=0.8))

  model.add(UpSampling2D())  # 24x32 -> 48x64
  model.add(Conv2D(256, kernel_size=kernel_size, padding="same"))
  model.add(Activation("relu"))
  model.add(BatchNormalization(momentum=0.8))

  model.add(UpSampling2D())  # 48x64 -> 96x128
  model.add(Conv2D(128, kernel_size=kernel_size, padding="same"))
  model.add(Activation("relu"))
  model.add(BatchNormalization(momentum=0.8))

  model.add(UpSampling2D())  # 96x128 -> 192x256
  model.add(Conv2D(64, kernel_size=kernel_size, padding="same"))
  model.add(Activation("relu"))
  model.add(BatchNormalization(momentum=0.8))

  model.add(Conv2D(32, kernel_size=kernel_size, padding="same"))
  model.add(Activation("relu"))
  model.add(BatchNormalization(momentum=0.8))

  model.add(Conv2D(channels, kernel_size=kernel_size, padding="same"))
  model.add(Activation("tanh"))

  model.summary()

  noise = Input(shape=noise_shape)
  img = model(noise)

  return Model(noise, img)

In [0]:
def build_discriminator():
  img_shape = (img_size[0], img_size[1], channels)

  model = Sequential()

  model.add(Conv2D(32, kernel_size=kernel_size, strides=2, input_shape=img_shape, padding="same"))  # 192x256 -> 96x128
  model.add(LeakyReLU(alpha=0.2))
  model.add(Dropout(0.25))

  model.add(Conv2D(64, kernel_size=kernel_size, strides=2, padding="same"))  # 96x128 -> 48x64
  model.add(ZeroPadding2D(padding=((0, 1), (0, 1))))
  model.add(LeakyReLU(alpha=0.2))
  model.add(Dropout(0.25))
  model.add(BatchNormalization(momentum=0.8))

  model.add(Conv2D(128, kernel_size=kernel_size, strides=2, padding="same"))  # 48x64 -> 24x32
  model.add(LeakyReLU(alpha=0.2))
  model.add(Dropout(0.25))
  model.add(BatchNormalization(momentum=0.8))

  model.add(Conv2D(256, kernel_size=kernel_size, strides=1, padding="same"))  # 24x32 -> 12x16
  model.add(LeakyReLU(alpha=0.2))
  model.add(Dropout(0.25))

  model.add(Conv2D(512, kernel_size=kernel_size, strides=1, padding="same"))  # 12x16 -> 6x8
  model.add(LeakyReLU(alpha=0.2))
  model.add(Dropout(0.25))

  model.add(Flatten())
  model.add(Dense(1, activation='sigmoid'))

  model.summary()

  img = Input(shape=img_shape)
  validity = model(img)

  return Model(img, validity)


In [0]:
def build_gan():
  optimizer = Adam(0.0002, 0.5)

  # See if the specified model paths exist, if they don't then we start training new models

  if os.path.exists(discriminator_path) and os.path.exists(generator_path):
      discriminator = load_model(discriminator_path)
      generator = load_model(generator_path)
      print("Loaded models...")
  else:
      discriminator = build_discriminator()
      discriminator.compile(loss='binary_crossentropy',
                                  optimizer=optimizer,
                                  metrics=['accuracy'])

      generator = build_generator()
      generator.compile(loss='binary_crossentropy', optimizer=optimizer)

  # These next few lines setup the training for the GAN model
  z = Input(shape=(100,))
  img = generator(z)

  discriminator.trainable = False

  valid = discriminator(img)

  combined = Model(z, valid)
  combined.compile(loss='binary_crossentropy', optimizer=optimizer)

  return (generator,discriminator,combined)

In [0]:
def train(epochs, image_path, batch_size=12, save_interval=20):
  generator,discriminator,combined = build_gan()
  
  X_train = load_imgs(image_path)
  print("Training Data Shape: ", X_train.shape)

  half_batch = batch_size // 2

  for epoch in range(epochs):
    # Train Generator
    noise = np.random.normal(0, 1, (batch_size, 100))
    g_loss = combined.train_on_batch(noise, np.ones((batch_size, 1)))

    # Train Discriminator
    idx = np.random.randint(0, X_train.shape[0], half_batch)
    imgs = []
    for img in idx:
      i = (X_train[img])
      # Rescale images from -1 to 1
      i = (i.astype(np.float32) - 127.5) / 127.5
      imgs.append(i)
    imgs = np.array(imgs)

    # Sample noise and generate a half batch of new images
    noise = np.random.normal(0, 1, (half_batch, 100))
    gen_imgs = generator.predict(noise)

    print(idx)
    print("epoch: images_shape: gen_images.shape: =", epoch, imgs.shape, gen_imgs.shape)

    # Train the discriminator (real classified as ones and generated as zeros)
    d_loss_real = discriminator.train_on_batch(imgs, np.ones((half_batch,1)))
    d_loss_fake = discriminator.train_on_batch(gen_imgs, np.zeros((half_batch, 1)))
    d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

    # Print progress
    print(f"{epoch} [D loss: {d_loss[0]} | D Accuracy: {100 * d_loss[1]}] [G loss: {g_loss}]")

    # If at save interval => save generated image samples, save model files
    if epoch % (save_interval) == 0:

      save_imgs(epoch,generator)

      if not os.path.exists(save_path):
          os.makedirs(save_path)
      discriminator.save(save_path + "/discrim.h5")
      generator.save(save_path + "/generat.h5")

In [0]:
def gene_imgs(count,generator):
  # Generate images from the currently loaded model
  noise = np.random.normal(0, 1, (count, 100))
  return generator.predict(noise)


In [0]:
def save_imgs(epoch, generator):
  r, c = 5, 5

  # Generates r*c images from the model, saves them individually and as a gallery

  imgs = gene_imgs(r*c,generator)
  imgs = 0.5 * imgs + 0.5

  print(imgs.shape)

  for i, img_array in enumerate(imgs):
      path = f"{output_directory}/generated_{img_size[0]}x{img_size[1]}"
      if not os.path.exists(path):
          os.makedirs(path)
      imageio.imwrite(path + f"/{epoch}_{i}_4.png", img_array)

  nindex, height, width, intensity = imgs.shape
  nrows = nindex // c
  assert nindex == nrows * c
  # want result.shape = (height*nrows, width*ncols, intensity)
  gallery = (imgs.reshape(nrows, c, height, width, intensity)
            .swapaxes(1, 2)
            .reshape(height * nrows, width * c, intensity))

  path = f"{output_directory}/gallery_generated_{img_size[0]}x{img_size[1]}"
  if not os.path.exists(path):
      os.makedirs(path)
  imageio.imwrite(path + f"/{epoch}_4.png", gallery)

In [0]:
def generate_imgs(count, threshold, modifier):
  generator,discriminator,combined = build_gan()

  # Generates (count) images from the model ensuring the discriminator scores them between the threshold values
  # and saves them

  imgs = []
  for i in range(count):
      score = [0]
      while not(threshold[0] < score[0] < threshold[1]):
          img = gene_imgs(1,generator)
          score = discriminator.predict(img)
      print("Image found: ", score[0])
      imgs.append(img)

  imgs = np.asarray(imgs).squeeze()
  imgs = 0.5 * imgs + 0.5

  print(imgs.shape)
  for i, img_array in enumerate(imgs):
      path = f"{output_directory}/generated_{threshold[0]}_{threshold[1]}"
      if not os.path.exists(path):
          os.makedirs(path)
      imageio.imwrite(path + f"/{modifier}_{i}.png", img_array)

In [0]:
train(epochs=1001, image_path=data_dir)





Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.









Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Loaded models...
Training Data Shape:  (986, 256, 256, 3)
[701 443  35 541 710 847]
epoch: images_shape: gen_images.shape: = 0 (6, 256, 256, 3) (6, 256, 256, 3)


/usr/local/lib/python3.6/dist-packages/keras/engine/training.py:493: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'


0 [D loss: 2.8727383613586426 | D Accuracy: 50.0] [G loss: 10.774041175842285]
(25, 256, 256, 3)


[776 521 817 777 536 796]
epoch: images_shape: gen_images.shape: = 1 (6, 256, 256, 3) (6, 256, 256, 3)
1 [D loss: 1.4997305870056152 | D Accuracy: 66.66666269302368] [G loss: 5.015303134918213]
[596 591 363  31 344 272]
epoch: images_shape: gen_images.shape: = 2 (6, 256, 256, 3) (6, 256, 256, 3)
2 [D loss: 0.06565388292074203 | D Accuracy: 100.0] [G loss: 11.684367179870605]
[756  64  38  25 647 361]
epoch: images_shape: gen_images.shape: = 3 (6, 256, 256, 3) (6, 256, 256, 3)
3 [D loss: 1.8225406408309937 | D Accuracy: 66.66666865348816] [G loss: 11.193977355957031]
[406 891 107 952 934 558]
epoch: images_shape: gen_images.shape: = 4 (6, 256, 256, 3) (6, 256, 256, 3)
4 [D loss: 0.5780744552612305 | D Accuracy: 75.0] [G loss: 7.683618545532227]
[689 150 147 124 658 215]
epoch: images_shape: gen_images.shape: = 5 (6, 256, 256, 3) (6, 256, 256, 3)
5 [D loss: 0.9996928572654724 | D Accuracy: 91.66666269302368] [G loss: 12.887896537780762]
[951 136  40 831 254 601]
epoch: images_shape: gen_

(25, 256, 256, 3)


[845 939 710 317 674 913]
epoch: images_shape: gen_images.shape: = 21 (6, 256, 256, 3) (6, 256, 256, 3)
21 [D loss: 1.0692332983016968 | D Accuracy: 75.0] [G loss: 5.816005229949951]
[835 828 715 295 664  22]
epoch: images_shape: gen_images.shape: = 22 (6, 256, 256, 3) (6, 256, 256, 3)
22 [D loss: 1.184416651725769 | D Accuracy: 66.66666865348816] [G loss: 8.12743091583252]
[670 394 917 954 720 107]
epoch: images_shape: gen_images.shape: = 23 (6, 256, 256, 3) (6, 256, 256, 3)
23 [D loss: 1.438323974609375 | D Accuracy: 75.0] [G loss: 7.480838775634766]
[178 906 774 629 631 815]
epoch: images_shape: gen_images.shape: = 24 (6, 256, 256, 3) (6, 256, 256, 3)
24 [D loss: 1.7122657299041748 | D Accuracy: 66.66666865348816] [G loss: 10.685452461242676]
[214 768 978 770  68 766]
epoch: images_shape: gen_images.shape: = 25 (6, 256, 256, 3) (6, 256, 256, 3)
25 [D loss: 1.6748015880584717 | D Accuracy: 58.33333730697632] [G loss: 7.683498382568359]
[350 298 479 356 839 465]
epoch: images_shape: g

(25, 256, 256, 3)


[707 760 545 716 944 253]
epoch: images_shape: gen_images.shape: = 41 (6, 256, 256, 3) (6, 256, 256, 3)
41 [D loss: 2.0188958644866943 | D Accuracy: 58.33333134651184] [G loss: 9.969573974609375]
[709 937 928 661  99 871]
epoch: images_shape: gen_images.shape: = 42 (6, 256, 256, 3) (6, 256, 256, 3)
42 [D loss: 0.32273662090301514 | D Accuracy: 91.66666269302368] [G loss: 3.531094789505005]
[180   7 175 676 284 609]
epoch: images_shape: gen_images.shape: = 43 (6, 256, 256, 3) (6, 256, 256, 3)
43 [D loss: 0.3069697320461273 | D Accuracy: 83.33333134651184] [G loss: 5.774251937866211]
[269 444 610 204 619 284]
epoch: images_shape: gen_images.shape: = 44 (6, 256, 256, 3) (6, 256, 256, 3)
44 [D loss: 0.6826301217079163 | D Accuracy: 83.33333134651184] [G loss: 5.8722100257873535]
[518 809 103 273   8  22]
epoch: images_shape: gen_images.shape: = 45 (6, 256, 256, 3) (6, 256, 256, 3)
45 [D loss: 0.22109226882457733 | D Accuracy: 91.66666269302368] [G loss: 9.307551383972168]
[514 513 753 707 

(25, 256, 256, 3)


[502 661 647 364 632 311]
epoch: images_shape: gen_images.shape: = 61 (6, 256, 256, 3) (6, 256, 256, 3)
61 [D loss: 1.199037790298462 | D Accuracy: 66.66666865348816] [G loss: 2.8151252269744873]
[283 207 412 921 635 795]
epoch: images_shape: gen_images.shape: = 62 (6, 256, 256, 3) (6, 256, 256, 3)
62 [D loss: 2.463031530380249 | D Accuracy: 75.0] [G loss: 8.056159973144531]
[692 953 598 863 961 441]
epoch: images_shape: gen_images.shape: = 63 (6, 256, 256, 3) (6, 256, 256, 3)
63 [D loss: 2.817283868789673 | D Accuracy: 66.66666865348816] [G loss: 13.537032127380371]
[165  20 695 369 332 624]
epoch: images_shape: gen_images.shape: = 64 (6, 256, 256, 3) (6, 256, 256, 3)
64 [D loss: 4.876550674438477 | D Accuracy: 50.0] [G loss: 6.1569085121154785]
[316 657 667 873 166  68]
epoch: images_shape: gen_images.shape: = 65 (6, 256, 256, 3) (6, 256, 256, 3)
65 [D loss: 0.560431957244873 | D Accuracy: 91.66666269302368] [G loss: 9.396244049072266]
[ 66 527 396 927 342 611]
epoch: images_shape: g

(25, 256, 256, 3)


[536 530  99 522 346 642]
epoch: images_shape: gen_images.shape: = 81 (6, 256, 256, 3) (6, 256, 256, 3)
81 [D loss: 3.5551204681396484 | D Accuracy: 66.66666865348816] [G loss: 4.197071552276611]
[169 607 816  35  79 614]
epoch: images_shape: gen_images.shape: = 82 (6, 256, 256, 3) (6, 256, 256, 3)
82 [D loss: 1.6554667949676514 | D Accuracy: 58.33333730697632] [G loss: 7.71300745010376]
[808 969  41 750 870 459]
epoch: images_shape: gen_images.shape: = 83 (6, 256, 256, 3) (6, 256, 256, 3)
83 [D loss: 2.718947410583496 | D Accuracy: 50.0] [G loss: 3.500229597091675]
[833 635 356  90 238 939]
epoch: images_shape: gen_images.shape: = 84 (6, 256, 256, 3) (6, 256, 256, 3)
84 [D loss: 1.7645370960235596 | D Accuracy: 66.66666269302368] [G loss: 9.563008308410645]
[635 685  63 810 241 934]
epoch: images_shape: gen_images.shape: = 85 (6, 256, 256, 3) (6, 256, 256, 3)
85 [D loss: 0.15281003713607788 | D Accuracy: 91.66666269302368] [G loss: 10.765620231628418]
[810 146 421 245 917 506]
epoch: 

(25, 256, 256, 3)


[166 581 727 397 545 672]
epoch: images_shape: gen_images.shape: = 101 (6, 256, 256, 3) (6, 256, 256, 3)
101 [D loss: 2.6604955196380615 | D Accuracy: 50.0] [G loss: 4.116252422332764]
[703 410 367 691 823 329]
epoch: images_shape: gen_images.shape: = 102 (6, 256, 256, 3) (6, 256, 256, 3)
102 [D loss: 2.500877618789673 | D Accuracy: 58.33333134651184] [G loss: 11.608482360839844]
[752 413 964  55 828 896]
epoch: images_shape: gen_images.shape: = 103 (6, 256, 256, 3) (6, 256, 256, 3)
103 [D loss: 0.24322544038295746 | D Accuracy: 91.66666269302368] [G loss: 12.47899341583252]
[105 550 970 335 302 688]
epoch: images_shape: gen_images.shape: = 104 (6, 256, 256, 3) (6, 256, 256, 3)
104 [D loss: 1.4386646747589111 | D Accuracy: 75.0] [G loss: 6.379133701324463]
[550 148 690 860 911 884]
epoch: images_shape: gen_images.shape: = 105 (6, 256, 256, 3) (6, 256, 256, 3)
105 [D loss: 3.360975503921509 | D Accuracy: 58.33333730697632] [G loss: 10.350314140319824]
[147 441 652 264 417 609]
epoch: im

(25, 256, 256, 3)


[155 637 167 963 752 280]
epoch: images_shape: gen_images.shape: = 121 (6, 256, 256, 3) (6, 256, 256, 3)
121 [D loss: 0.4263383448123932 | D Accuracy: 83.33333134651184] [G loss: 6.160860538482666]
[729 521 268 873 447 823]
epoch: images_shape: gen_images.shape: = 122 (6, 256, 256, 3) (6, 256, 256, 3)
122 [D loss: 3.206503391265869 | D Accuracy: 50.0] [G loss: 7.9227471351623535]
[366 208 630 939 345 294]
epoch: images_shape: gen_images.shape: = 123 (6, 256, 256, 3) (6, 256, 256, 3)
123 [D loss: 0.4748739004135132 | D Accuracy: 91.66666269302368] [G loss: 8.578564643859863]
[856 586 415 911 233 320]
epoch: images_shape: gen_images.shape: = 124 (6, 256, 256, 3) (6, 256, 256, 3)
124 [D loss: 0.3068276643753052 | D Accuracy: 83.33333730697632] [G loss: 9.069377899169922]
[760 140 491 878 872 247]
epoch: images_shape: gen_images.shape: = 125 (6, 256, 256, 3) (6, 256, 256, 3)
125 [D loss: 2.5170013904571533 | D Accuracy: 41.66666865348816] [G loss: 4.605024337768555]
[ 75 816 291  25 851 17

(25, 256, 256, 3)


[146 750 248 861   7 853]
epoch: images_shape: gen_images.shape: = 141 (6, 256, 256, 3) (6, 256, 256, 3)
141 [D loss: 1.2318681478500366 | D Accuracy: 50.0] [G loss: 9.456332206726074]
[761  26 252 728 211 565]
epoch: images_shape: gen_images.shape: = 142 (6, 256, 256, 3) (6, 256, 256, 3)
142 [D loss: 2.5708415508270264 | D Accuracy: 50.0] [G loss: 14.7510404586792]
[735 536 949 699 875 705]
epoch: images_shape: gen_images.shape: = 143 (6, 256, 256, 3) (6, 256, 256, 3)
143 [D loss: 0.5293618440628052 | D Accuracy: 91.66666269302368] [G loss: 13.574657440185547]
[736 367 629 237  96 783]
epoch: images_shape: gen_images.shape: = 144 (6, 256, 256, 3) (6, 256, 256, 3)
144 [D loss: 1.3793914318084717 | D Accuracy: 75.0] [G loss: 14.609241485595703]
[174 113 215 663 127 402]
epoch: images_shape: gen_images.shape: = 145 (6, 256, 256, 3) (6, 256, 256, 3)
145 [D loss: 1.019965410232544 | D Accuracy: 83.33333730697632] [G loss: 9.74450397491455]
[621  84 446 218 764 791]
epoch: images_shape: gen

(25, 256, 256, 3)


[853 943 172 200 744 229]
epoch: images_shape: gen_images.shape: = 161 (6, 256, 256, 3) (6, 256, 256, 3)
161 [D loss: 2.410933017730713 | D Accuracy: 66.66666865348816] [G loss: 13.492690086364746]
[713 675 187 357 457 522]
epoch: images_shape: gen_images.shape: = 162 (6, 256, 256, 3) (6, 256, 256, 3)
162 [D loss: 2.9905548095703125 | D Accuracy: 75.0] [G loss: 10.855167388916016]
[548 870 955 254 241 148]
epoch: images_shape: gen_images.shape: = 163 (6, 256, 256, 3) (6, 256, 256, 3)
163 [D loss: 3.0681817531585693 | D Accuracy: 50.0] [G loss: 6.787574291229248]
[533 892  27 917 592 911]
epoch: images_shape: gen_images.shape: = 164 (6, 256, 256, 3) (6, 256, 256, 3)
164 [D loss: 1.1601109504699707 | D Accuracy: 75.0] [G loss: 3.294384002685547]
[102 830  45 875 687 158]
epoch: images_shape: gen_images.shape: = 165 (6, 256, 256, 3) (6, 256, 256, 3)
165 [D loss: 0.4745270609855652 | D Accuracy: 91.66666269302368] [G loss: 14.300639152526855]
[825 168 582 331 912 926]
epoch: images_shape: 

(25, 256, 256, 3)


[180 169 773 559 243 236]
epoch: images_shape: gen_images.shape: = 181 (6, 256, 256, 3) (6, 256, 256, 3)
181 [D loss: 1.171185851097107 | D Accuracy: 75.0] [G loss: 14.42544174194336]
[898  55  21 889 202 301]
epoch: images_shape: gen_images.shape: = 182 (6, 256, 256, 3) (6, 256, 256, 3)
182 [D loss: 0.9864228367805481 | D Accuracy: 75.0] [G loss: 13.841270446777344]
[735 803 173 768 699 821]
epoch: images_shape: gen_images.shape: = 183 (6, 256, 256, 3) (6, 256, 256, 3)
183 [D loss: 1.0431137084960938 | D Accuracy: 83.33333134651184] [G loss: 9.404586791992188]
[611 937 264 642  79 937]
epoch: images_shape: gen_images.shape: = 184 (6, 256, 256, 3) (6, 256, 256, 3)
184 [D loss: 1.9419851303100586 | D Accuracy: 50.0] [G loss: 10.646807670593262]
[462 147 637 946 660 966]
epoch: images_shape: gen_images.shape: = 185 (6, 256, 256, 3) (6, 256, 256, 3)
185 [D loss: 0.7570112943649292 | D Accuracy: 66.66666269302368] [G loss: 7.455656051635742]
[725 622 869  27 415 390]
epoch: images_shape: g

(25, 256, 256, 3)


[975 364 798 396 937 234]
epoch: images_shape: gen_images.shape: = 201 (6, 256, 256, 3) (6, 256, 256, 3)
201 [D loss: 1.7695494890213013 | D Accuracy: 75.0] [G loss: 13.306992530822754]
[715 677 610 102 872 141]
epoch: images_shape: gen_images.shape: = 202 (6, 256, 256, 3) (6, 256, 256, 3)
202 [D loss: 2.9433188438415527 | D Accuracy: 33.33333432674408] [G loss: 12.034462928771973]
[299 845 831  91 777 702]
epoch: images_shape: gen_images.shape: = 203 (6, 256, 256, 3) (6, 256, 256, 3)
203 [D loss: 0.4288657009601593 | D Accuracy: 91.66666269302368] [G loss: 7.096083164215088]
[630 352 892 224 820 909]
epoch: images_shape: gen_images.shape: = 204 (6, 256, 256, 3) (6, 256, 256, 3)
204 [D loss: 1.9967398643493652 | D Accuracy: 66.66666865348816] [G loss: 9.142416954040527]
[334 651 902 875 674 744]
epoch: images_shape: gen_images.shape: = 205 (6, 256, 256, 3) (6, 256, 256, 3)
205 [D loss: 2.062973976135254 | D Accuracy: 58.33333730697632] [G loss: 8.185812950134277]
[837 460 710 564 117  

(25, 256, 256, 3)


[556  34 784  30 468 776]
epoch: images_shape: gen_images.shape: = 221 (6, 256, 256, 3) (6, 256, 256, 3)
221 [D loss: 2.4929943084716797 | D Accuracy: 58.33333730697632] [G loss: 6.252938747406006]
[871 387 762 256 213 356]
epoch: images_shape: gen_images.shape: = 222 (6, 256, 256, 3) (6, 256, 256, 3)
222 [D loss: 2.285850763320923 | D Accuracy: 66.66666865348816] [G loss: 8.573775291442871]
[674  15 611 910 681  84]
epoch: images_shape: gen_images.shape: = 223 (6, 256, 256, 3) (6, 256, 256, 3)
223 [D loss: 0.23068487644195557 | D Accuracy: 83.33333134651184] [G loss: 8.244267463684082]
[283 430 821 550 599 979]
epoch: images_shape: gen_images.shape: = 224 (6, 256, 256, 3) (6, 256, 256, 3)
224 [D loss: 0.6299909949302673 | D Accuracy: 66.66666865348816] [G loss: 10.206881523132324]
[551 256 239 705 580 953]
epoch: images_shape: gen_images.shape: = 225 (6, 256, 256, 3) (6, 256, 256, 3)
225 [D loss: 1.468352198600769 | D Accuracy: 83.33333134651184] [G loss: 7.661951541900635]
[562  71 7

(25, 256, 256, 3)


[620 146 586 113  61 860]
epoch: images_shape: gen_images.shape: = 241 (6, 256, 256, 3) (6, 256, 256, 3)
241 [D loss: 5.089513778686523 | D Accuracy: 8.33333358168602] [G loss: 5.875911235809326]
[223 899 627 243 775 809]
epoch: images_shape: gen_images.shape: = 242 (6, 256, 256, 3) (6, 256, 256, 3)
242 [D loss: 0.7971025109291077 | D Accuracy: 58.33333730697632] [G loss: 7.974460601806641]
[822 341 845 775 549 553]
epoch: images_shape: gen_images.shape: = 243 (6, 256, 256, 3) (6, 256, 256, 3)
243 [D loss: 1.382089614868164 | D Accuracy: 58.33333730697632] [G loss: 9.997078895568848]
[581 621 684 682  92  49]
epoch: images_shape: gen_images.shape: = 244 (6, 256, 256, 3) (6, 256, 256, 3)
244 [D loss: 0.5519286394119263 | D Accuracy: 91.66666269302368] [G loss: 9.109969139099121]
[932 366 802 983 827 409]
epoch: images_shape: gen_images.shape: = 245 (6, 256, 256, 3) (6, 256, 256, 3)
245 [D loss: 5.269914627075195 | D Accuracy: 33.33333432674408] [G loss: 10.47486686706543]
[460 311 510 4

(25, 256, 256, 3)


[602 936  31 874 181 349]
epoch: images_shape: gen_images.shape: = 261 (6, 256, 256, 3) (6, 256, 256, 3)
261 [D loss: 1.8629730939865112 | D Accuracy: 66.66666269302368] [G loss: 11.432255744934082]
[265 553  24 381  46 413]
epoch: images_shape: gen_images.shape: = 262 (6, 256, 256, 3) (6, 256, 256, 3)
262 [D loss: 2.723870038986206 | D Accuracy: 58.33333730697632] [G loss: 9.828320503234863]
[465 112 838 925 833 880]
epoch: images_shape: gen_images.shape: = 263 (6, 256, 256, 3) (6, 256, 256, 3)
263 [D loss: 1.5846359729766846 | D Accuracy: 66.66666269302368] [G loss: 8.96521282196045]
[124 336 770 873 835 772]
epoch: images_shape: gen_images.shape: = 264 (6, 256, 256, 3) (6, 256, 256, 3)
264 [D loss: 4.418724536895752 | D Accuracy: 41.66666567325592] [G loss: 5.444377422332764]
[433 455 927 580 383 686]
epoch: images_shape: gen_images.shape: = 265 (6, 256, 256, 3) (6, 256, 256, 3)
265 [D loss: 1.4812533855438232 | D Accuracy: 66.66666269302368] [G loss: 13.171036720275879]
[147 220 11

(25, 256, 256, 3)


[231 359 425  82 720 199]
epoch: images_shape: gen_images.shape: = 281 (6, 256, 256, 3) (6, 256, 256, 3)
281 [D loss: 0.49301135540008545 | D Accuracy: 83.33333134651184] [G loss: 8.049836158752441]
[ 81 300 931 154 211 678]
epoch: images_shape: gen_images.shape: = 282 (6, 256, 256, 3) (6, 256, 256, 3)
282 [D loss: 2.5014238357543945 | D Accuracy: 58.33333730697632] [G loss: 7.823129177093506]
[278 894 677  64 514 712]
epoch: images_shape: gen_images.shape: = 283 (6, 256, 256, 3) (6, 256, 256, 3)
283 [D loss: 0.7997512221336365 | D Accuracy: 83.33333730697632] [G loss: 11.838269233703613]
[292 218 759 614 640 965]
epoch: images_shape: gen_images.shape: = 284 (6, 256, 256, 3) (6, 256, 256, 3)
284 [D loss: 2.6488802433013916 | D Accuracy: 50.0] [G loss: 3.2973031997680664]
[314 646 961 779   3 535]
epoch: images_shape: gen_images.shape: = 285 (6, 256, 256, 3) (6, 256, 256, 3)
285 [D loss: 2.5408012866973877 | D Accuracy: 58.33333730697632] [G loss: 6.828819274902344]
[258 328 454 152 617

(25, 256, 256, 3)


[594 878 550 704  37 635]
epoch: images_shape: gen_images.shape: = 301 (6, 256, 256, 3) (6, 256, 256, 3)
301 [D loss: 2.910290479660034 | D Accuracy: 58.33333134651184] [G loss: 3.9476325511932373]
[666 402 265 367  45 334]
epoch: images_shape: gen_images.shape: = 302 (6, 256, 256, 3) (6, 256, 256, 3)
302 [D loss: 2.4042177200317383 | D Accuracy: 58.33333730697632] [G loss: 9.421782493591309]
[685 860 226   1 117 169]
epoch: images_shape: gen_images.shape: = 303 (6, 256, 256, 3) (6, 256, 256, 3)
303 [D loss: 0.40556490421295166 | D Accuracy: 91.66666269302368] [G loss: 10.223907470703125]
[131 604 823  80 258 564]
epoch: images_shape: gen_images.shape: = 304 (6, 256, 256, 3) (6, 256, 256, 3)
304 [D loss: 1.4091401100158691 | D Accuracy: 66.66666269302368] [G loss: 8.140400886535645]
[  6 933 480 458  89  22]
epoch: images_shape: gen_images.shape: = 305 (6, 256, 256, 3) (6, 256, 256, 3)
305 [D loss: 2.274472951889038 | D Accuracy: 50.0] [G loss: 8.016818046569824]
[541 484 309 324 160 7

(25, 256, 256, 3)


[863 956 826  87 625 910]
epoch: images_shape: gen_images.shape: = 321 (6, 256, 256, 3) (6, 256, 256, 3)
321 [D loss: 3.6949691772460938 | D Accuracy: 33.33333432674408] [G loss: 10.269915580749512]
[968 298 654 582  93 295]
epoch: images_shape: gen_images.shape: = 322 (6, 256, 256, 3) (6, 256, 256, 3)
322 [D loss: 1.4813365936279297 | D Accuracy: 75.0] [G loss: 10.249421119689941]
[817 596 303 562 482 952]
epoch: images_shape: gen_images.shape: = 323 (6, 256, 256, 3) (6, 256, 256, 3)
323 [D loss: 5.491750240325928 | D Accuracy: 25.0] [G loss: 4.521215438842773]
[653 616 975 128 487  42]
epoch: images_shape: gen_images.shape: = 324 (6, 256, 256, 3) (6, 256, 256, 3)
324 [D loss: 1.8510905504226685 | D Accuracy: 75.0] [G loss: 8.686077117919922]
[ 49  86 566 653 779 789]
epoch: images_shape: gen_images.shape: = 325 (6, 256, 256, 3) (6, 256, 256, 3)
325 [D loss: 1.0622961521148682 | D Accuracy: 66.66666865348816] [G loss: 11.170886993408203]
[288 317 906 866 406 258]
epoch: images_shape: 

(25, 256, 256, 3)


[763 657 617 457 720 465]
epoch: images_shape: gen_images.shape: = 341 (6, 256, 256, 3) (6, 256, 256, 3)
341 [D loss: 2.4721057415008545 | D Accuracy: 66.66666865348816] [G loss: 6.854365825653076]
[316 546 121 946 859 783]
epoch: images_shape: gen_images.shape: = 342 (6, 256, 256, 3) (6, 256, 256, 3)
342 [D loss: 2.7206156253814697 | D Accuracy: 50.0] [G loss: 10.916581153869629]
[630 297 456 359 332 202]
epoch: images_shape: gen_images.shape: = 343 (6, 256, 256, 3) (6, 256, 256, 3)
343 [D loss: 2.900897979736328 | D Accuracy: 41.66666865348816] [G loss: 9.321235656738281]
[830 663 700 245 497 551]
epoch: images_shape: gen_images.shape: = 344 (6, 256, 256, 3) (6, 256, 256, 3)
344 [D loss: 2.918410301208496 | D Accuracy: 66.66666269302368] [G loss: 12.255372047424316]
[933  61 363 561  84 544]
epoch: images_shape: gen_images.shape: = 345 (6, 256, 256, 3) (6, 256, 256, 3)
345 [D loss: 0.1414918601512909 | D Accuracy: 91.66666269302368] [G loss: 11.469497680664062]
[907 679 743 248 628 3

(25, 256, 256, 3)


[283 879 870 813 490 980]
epoch: images_shape: gen_images.shape: = 361 (6, 256, 256, 3) (6, 256, 256, 3)
361 [D loss: 1.3864612579345703 | D Accuracy: 75.0] [G loss: 6.2371697425842285]
[159 875 940 947 341 417]
epoch: images_shape: gen_images.shape: = 362 (6, 256, 256, 3) (6, 256, 256, 3)
362 [D loss: 3.265455484390259 | D Accuracy: 50.0] [G loss: 5.445335865020752]
[567 241 760 461 301 739]
epoch: images_shape: gen_images.shape: = 363 (6, 256, 256, 3) (6, 256, 256, 3)
363 [D loss: 1.1474668979644775 | D Accuracy: 66.66666269302368] [G loss: 12.64041519165039]
[ 82 258  92 396 454 101]
epoch: images_shape: gen_images.shape: = 364 (6, 256, 256, 3) (6, 256, 256, 3)
364 [D loss: 0.060976237058639526 | D Accuracy: 91.66666269302368] [G loss: 13.7787504196167]
[560 558 983 334 723 903]
epoch: images_shape: gen_images.shape: = 365 (6, 256, 256, 3) (6, 256, 256, 3)
365 [D loss: 1.1416817903518677 | D Accuracy: 83.33333134651184] [G loss: 9.08689022064209]
[703 500 584 621 834 371]
epoch: ima

(25, 256, 256, 3)


[ 33 283 820 419 798 459]
epoch: images_shape: gen_images.shape: = 381 (6, 256, 256, 3) (6, 256, 256, 3)
381 [D loss: 2.0860636234283447 | D Accuracy: 41.66666865348816] [G loss: 4.41491174697876]
[957  87 942 496  92 215]
epoch: images_shape: gen_images.shape: = 382 (6, 256, 256, 3) (6, 256, 256, 3)
382 [D loss: 1.0475685596466064 | D Accuracy: 83.33333134651184] [G loss: 3.8361740112304688]
[539 941 504 945 638  79]
epoch: images_shape: gen_images.shape: = 383 (6, 256, 256, 3) (6, 256, 256, 3)
383 [D loss: 1.7210787534713745 | D Accuracy: 58.33333730697632] [G loss: 9.56722354888916]
[622 723 495 874 621 583]
epoch: images_shape: gen_images.shape: = 384 (6, 256, 256, 3) (6, 256, 256, 3)
384 [D loss: 0.4834289848804474 | D Accuracy: 75.0] [G loss: 8.29686450958252]
[822 129 596 728 448   3]
epoch: images_shape: gen_images.shape: = 385 (6, 256, 256, 3) (6, 256, 256, 3)
385 [D loss: 1.415642261505127 | D Accuracy: 66.66666865348816] [G loss: 8.121495246887207]
[856 250 458 768 891 153]


(25, 256, 256, 3)


[802 631 211 882 883 274]
epoch: images_shape: gen_images.shape: = 401 (6, 256, 256, 3) (6, 256, 256, 3)
401 [D loss: 0.9780042767524719 | D Accuracy: 75.0] [G loss: 9.245784759521484]
[500 864 839 610 367  72]
epoch: images_shape: gen_images.shape: = 402 (6, 256, 256, 3) (6, 256, 256, 3)
402 [D loss: 2.9424688816070557 | D Accuracy: 66.66666269302368] [G loss: 14.633537292480469]
[218 132 163 149 542 485]
epoch: images_shape: gen_images.shape: = 403 (6, 256, 256, 3) (6, 256, 256, 3)
403 [D loss: 1.6699031591415405 | D Accuracy: 66.66666865348816] [G loss: 10.226819038391113]
[944 424 322 818 184  69]
epoch: images_shape: gen_images.shape: = 404 (6, 256, 256, 3) (6, 256, 256, 3)
404 [D loss: 1.4314322471618652 | D Accuracy: 58.33333730697632] [G loss: 8.442112922668457]
[314 922 240 717 398 526]
epoch: images_shape: gen_images.shape: = 405 (6, 256, 256, 3) (6, 256, 256, 3)
405 [D loss: 2.3868110179901123 | D Accuracy: 41.66666865348816] [G loss: 7.735862731933594]
[223 956 180  30 277 

(25, 256, 256, 3)


[964 597  23 333 575 124]
epoch: images_shape: gen_images.shape: = 421 (6, 256, 256, 3) (6, 256, 256, 3)
421 [D loss: 1.2519748210906982 | D Accuracy: 75.0] [G loss: 9.863066673278809]
[595   5   6 839 184 970]
epoch: images_shape: gen_images.shape: = 422 (6, 256, 256, 3) (6, 256, 256, 3)
422 [D loss: 0.19535963237285614 | D Accuracy: 91.66666269302368] [G loss: 12.286660194396973]
[177 944 237 822 584 423]
epoch: images_shape: gen_images.shape: = 423 (6, 256, 256, 3) (6, 256, 256, 3)
423 [D loss: 1.752109169960022 | D Accuracy: 75.0] [G loss: 12.289012908935547]
[261 928 341 871  63 806]
epoch: images_shape: gen_images.shape: = 424 (6, 256, 256, 3) (6, 256, 256, 3)
424 [D loss: 1.39071524143219 | D Accuracy: 75.0] [G loss: 12.705113410949707]
[599 943 779 897 638  72]
epoch: images_shape: gen_images.shape: = 425 (6, 256, 256, 3) (6, 256, 256, 3)
425 [D loss: 1.714402198791504 | D Accuracy: 66.66666269302368] [G loss: 9.4210844039917]
[ 74 716 111 439  13  56]
epoch: images_shape: gen_

(25, 256, 256, 3)


[853 870 635 236 470 104]
epoch: images_shape: gen_images.shape: = 441 (6, 256, 256, 3) (6, 256, 256, 3)
441 [D loss: 1.1763553619384766 | D Accuracy: 75.0] [G loss: 14.773770332336426]
[509   4 807 480 159 874]
epoch: images_shape: gen_images.shape: = 442 (6, 256, 256, 3) (6, 256, 256, 3)
442 [D loss: 1.2783350944519043 | D Accuracy: 75.0] [G loss: 6.93848991394043]
[ 89 554 533 951 606 759]
epoch: images_shape: gen_images.shape: = 443 (6, 256, 256, 3) (6, 256, 256, 3)
443 [D loss: 0.8303558826446533 | D Accuracy: 83.33333134651184] [G loss: 7.373657703399658]
[968 162 491 626 456 531]
epoch: images_shape: gen_images.shape: = 444 (6, 256, 256, 3) (6, 256, 256, 3)
444 [D loss: 0.8026595711708069 | D Accuracy: 66.66666865348816] [G loss: 6.910935878753662]
[680 137 643 137  63 378]
epoch: images_shape: gen_images.shape: = 445 (6, 256, 256, 3) (6, 256, 256, 3)
445 [D loss: 2.6749660968780518 | D Accuracy: 41.66666865348816] [G loss: 10.170306205749512]
[165 674 190 807 235 344]
epoch: im

(25, 256, 256, 3)


[668 694 896 460 688 462]
epoch: images_shape: gen_images.shape: = 461 (6, 256, 256, 3) (6, 256, 256, 3)
461 [D loss: 1.1951394081115723 | D Accuracy: 75.0] [G loss: 5.818408489227295]
[424 393  20 526 393 772]
epoch: images_shape: gen_images.shape: = 462 (6, 256, 256, 3) (6, 256, 256, 3)
462 [D loss: 0.05440683662891388 | D Accuracy: 100.0] [G loss: 11.00002670288086]
[871 243 169 477 977 662]
epoch: images_shape: gen_images.shape: = 463 (6, 256, 256, 3) (6, 256, 256, 3)
463 [D loss: 1.6888697147369385 | D Accuracy: 66.66666269302368] [G loss: 10.739630699157715]
[339 736 512 669 834 124]
epoch: images_shape: gen_images.shape: = 464 (6, 256, 256, 3) (6, 256, 256, 3)
464 [D loss: 0.20911505818367004 | D Accuracy: 83.33333134651184] [G loss: 8.239631652832031]
[406 652 156 752  12 407]
epoch: images_shape: gen_images.shape: = 465 (6, 256, 256, 3) (6, 256, 256, 3)
465 [D loss: 0.8744651079177856 | D Accuracy: 83.33333134651184] [G loss: 4.760307788848877]
[282 746 235  21 856 710]
epoch:

(25, 256, 256, 3)


[309 574 656 550 796 430]
epoch: images_shape: gen_images.shape: = 481 (6, 256, 256, 3) (6, 256, 256, 3)
481 [D loss: 1.4315824508666992 | D Accuracy: 66.66666865348816] [G loss: 7.045112609863281]
[438 666 682 170 143 913]
epoch: images_shape: gen_images.shape: = 482 (6, 256, 256, 3) (6, 256, 256, 3)
482 [D loss: 0.9973118305206299 | D Accuracy: 58.33333134651184] [G loss: 9.475533485412598]
[949 310 184  33 385 892]
epoch: images_shape: gen_images.shape: = 483 (6, 256, 256, 3) (6, 256, 256, 3)
483 [D loss: 3.448017120361328 | D Accuracy: 41.66666865348816] [G loss: 4.995119571685791]
[ 47 594 871 407 144  41]
epoch: images_shape: gen_images.shape: = 484 (6, 256, 256, 3) (6, 256, 256, 3)
484 [D loss: 1.2547205686569214 | D Accuracy: 75.0] [G loss: 15.007454872131348]
[450 179 738 667  75 598]
epoch: images_shape: gen_images.shape: = 485 (6, 256, 256, 3) (6, 256, 256, 3)
485 [D loss: 1.2586597204208374 | D Accuracy: 83.33333730697632] [G loss: 15.063003540039062]
[ 85 574 400 169 263 4

(25, 256, 256, 3)


[283 533 157 448 385 569]
epoch: images_shape: gen_images.shape: = 501 (6, 256, 256, 3) (6, 256, 256, 3)
501 [D loss: 3.0952186584472656 | D Accuracy: 75.0] [G loss: 13.914097785949707]
[775 980 931 886 184 404]
epoch: images_shape: gen_images.shape: = 502 (6, 256, 256, 3) (6, 256, 256, 3)
502 [D loss: 0.3496488332748413 | D Accuracy: 91.66666269302368] [G loss: 15.920350074768066]
[699  24 602 865 773 347]
epoch: images_shape: gen_images.shape: = 503 (6, 256, 256, 3) (6, 256, 256, 3)
503 [D loss: 1.5699492692947388 | D Accuracy: 58.33333730697632] [G loss: 11.572097778320312]
[344 445  39 224 247 133]
epoch: images_shape: gen_images.shape: = 504 (6, 256, 256, 3) (6, 256, 256, 3)
504 [D loss: 1.0980168581008911 | D Accuracy: 83.33333134651184] [G loss: 7.731178283691406]
[786 662 735  46  84 345]
epoch: images_shape: gen_images.shape: = 505 (6, 256, 256, 3) (6, 256, 256, 3)
505 [D loss: 2.605381488800049 | D Accuracy: 41.66666865348816] [G loss: 4.874181270599365]
[904 202 786 218 728 

(25, 256, 256, 3)


[636 151   6 463 394 267]
epoch: images_shape: gen_images.shape: = 521 (6, 256, 256, 3) (6, 256, 256, 3)
521 [D loss: 1.012568473815918 | D Accuracy: 75.0] [G loss: 6.729332447052002]
[ 31 736 131 849 984 951]
epoch: images_shape: gen_images.shape: = 522 (6, 256, 256, 3) (6, 256, 256, 3)
522 [D loss: 0.3702564239501953 | D Accuracy: 83.33333134651184] [G loss: 6.7936625480651855]
[167 155   2 385 225 202]
epoch: images_shape: gen_images.shape: = 523 (6, 256, 256, 3) (6, 256, 256, 3)
523 [D loss: 0.28325343132019043 | D Accuracy: 75.0] [G loss: 11.608908653259277]
[906 697 467 952  90 169]
epoch: images_shape: gen_images.shape: = 524 (6, 256, 256, 3) (6, 256, 256, 3)
524 [D loss: 2.125368356704712 | D Accuracy: 50.0] [G loss: 9.061447143554688]
[810 969 221 424 164 293]
epoch: images_shape: gen_images.shape: = 525 (6, 256, 256, 3) (6, 256, 256, 3)
525 [D loss: 0.9576506614685059 | D Accuracy: 83.33333134651184] [G loss: 6.714937210083008]
[124 545 302 686 186 277]
epoch: images_shape: g

(25, 256, 256, 3)


[543 475 689 874 199 734]
epoch: images_shape: gen_images.shape: = 541 (6, 256, 256, 3) (6, 256, 256, 3)
541 [D loss: 2.434227705001831 | D Accuracy: 58.33333134651184] [G loss: 7.17254638671875]
[583 679 763 561 241 928]
epoch: images_shape: gen_images.shape: = 542 (6, 256, 256, 3) (6, 256, 256, 3)
542 [D loss: 1.371253490447998 | D Accuracy: 83.33333730697632] [G loss: 9.420695304870605]
[ 33 418  85 427 176 510]
epoch: images_shape: gen_images.shape: = 543 (6, 256, 256, 3) (6, 256, 256, 3)
543 [D loss: 3.0271897315979004 | D Accuracy: 58.33333730697632] [G loss: 9.243962287902832]
[767 566 728 446 359 878]
epoch: images_shape: gen_images.shape: = 544 (6, 256, 256, 3) (6, 256, 256, 3)
544 [D loss: 0.6914929747581482 | D Accuracy: 66.66666865348816] [G loss: 6.216800689697266]
[295 905 462  23 828 713]
epoch: images_shape: gen_images.shape: = 545 (6, 256, 256, 3) (6, 256, 256, 3)
545 [D loss: 2.5903570652008057 | D Accuracy: 66.66666865348816] [G loss: 8.414204597473145]
[663 943 131 

(25, 256, 256, 3)


[971 421 680 741 912 176]
epoch: images_shape: gen_images.shape: = 561 (6, 256, 256, 3) (6, 256, 256, 3)
561 [D loss: 2.14544939994812 | D Accuracy: 50.0] [G loss: 11.72510051727295]
[235 574  89 139 299 188]
epoch: images_shape: gen_images.shape: = 562 (6, 256, 256, 3) (6, 256, 256, 3)
562 [D loss: 0.8204286694526672 | D Accuracy: 91.66666269302368] [G loss: 14.252093315124512]
[455 947 655 580 769 370]
epoch: images_shape: gen_images.shape: = 563 (6, 256, 256, 3) (6, 256, 256, 3)
563 [D loss: 1.0527654886245728 | D Accuracy: 83.33333730697632] [G loss: 15.814544677734375]
[584 166 169 833 488 125]
epoch: images_shape: gen_images.shape: = 564 (6, 256, 256, 3) (6, 256, 256, 3)
564 [D loss: 1.0410135984420776 | D Accuracy: 83.33333134651184] [G loss: 11.844715118408203]
[446 923 705 662 860 561]
epoch: images_shape: gen_images.shape: = 565 (6, 256, 256, 3) (6, 256, 256, 3)
565 [D loss: 1.7924349308013916 | D Accuracy: 66.66666865348816] [G loss: 7.645540714263916]
[231 191 955 726 776 2

(25, 256, 256, 3)


[836 808  84 878 495 393]
epoch: images_shape: gen_images.shape: = 581 (6, 256, 256, 3) (6, 256, 256, 3)
581 [D loss: 2.341597318649292 | D Accuracy: 58.33333730697632] [G loss: 7.079081058502197]
[861 308 770 507 585 615]
epoch: images_shape: gen_images.shape: = 582 (6, 256, 256, 3) (6, 256, 256, 3)
582 [D loss: 1.8609459400177002 | D Accuracy: 75.0] [G loss: 7.280649662017822]
[696 680  91 169 868 658]
epoch: images_shape: gen_images.shape: = 583 (6, 256, 256, 3) (6, 256, 256, 3)
583 [D loss: 4.571930408477783 | D Accuracy: 33.33333432674408] [G loss: 8.15678882598877]
[195 908 921 650 241 409]
epoch: images_shape: gen_images.shape: = 584 (6, 256, 256, 3) (6, 256, 256, 3)
584 [D loss: 3.3909499645233154 | D Accuracy: 41.66666865348816] [G loss: 11.628753662109375]
[448 175 173 358 308 497]
epoch: images_shape: gen_images.shape: = 585 (6, 256, 256, 3) (6, 256, 256, 3)
585 [D loss: 1.992832899093628 | D Accuracy: 75.0] [G loss: 14.380671501159668]
[ 31 100 474 546 226 635]
epoch: image

(25, 256, 256, 3)


[783 910 155 320 777 925]
epoch: images_shape: gen_images.shape: = 601 (6, 256, 256, 3) (6, 256, 256, 3)
601 [D loss: 1.7016396522521973 | D Accuracy: 66.66666269302368] [G loss: 9.517828941345215]
[176 824 303 299 199 342]
epoch: images_shape: gen_images.shape: = 602 (6, 256, 256, 3) (6, 256, 256, 3)
602 [D loss: 1.4727544784545898 | D Accuracy: 83.33333730697632] [G loss: 11.175692558288574]
[417  93 743 886 447 444]
epoch: images_shape: gen_images.shape: = 603 (6, 256, 256, 3) (6, 256, 256, 3)
603 [D loss: 2.999976634979248 | D Accuracy: 50.0] [G loss: 6.1452202796936035]
[866 221 215 871 641 544]
epoch: images_shape: gen_images.shape: = 604 (6, 256, 256, 3) (6, 256, 256, 3)
604 [D loss: 0.9080846309661865 | D Accuracy: 83.33333730697632] [G loss: 8.5551176071167]
[871 936 629  53 175 438]
epoch: images_shape: gen_images.shape: = 605 (6, 256, 256, 3) (6, 256, 256, 3)
605 [D loss: 4.440376281738281 | D Accuracy: 33.33333432674408] [G loss: 7.934507846832275]
[725 588 259 595 596 731]

(25, 256, 256, 3)


[202 495 146 546 838 335]
epoch: images_shape: gen_images.shape: = 621 (6, 256, 256, 3) (6, 256, 256, 3)
621 [D loss: 3.960035562515259 | D Accuracy: 58.33333134651184] [G loss: 6.814958572387695]
[337 812 566 756  29 665]
epoch: images_shape: gen_images.shape: = 622 (6, 256, 256, 3) (6, 256, 256, 3)
622 [D loss: 1.1414706707000732 | D Accuracy: 75.0] [G loss: 8.447648048400879]
[ 78 636 188 924 749 904]
epoch: images_shape: gen_images.shape: = 623 (6, 256, 256, 3) (6, 256, 256, 3)
623 [D loss: 2.8098652362823486 | D Accuracy: 58.33333134651184] [G loss: 7.8950018882751465]
[ 27  12  45  45 221 969]
epoch: images_shape: gen_images.shape: = 624 (6, 256, 256, 3) (6, 256, 256, 3)
624 [D loss: 1.058734655380249 | D Accuracy: 83.33333730697632] [G loss: 2.127171039581299]
[317 855  35 796 414 585]
epoch: images_shape: gen_images.shape: = 625 (6, 256, 256, 3) (6, 256, 256, 3)
625 [D loss: 2.241584062576294 | D Accuracy: 66.66666865348816] [G loss: 5.451005458831787]
[339 272  16 337 938 533]

(25, 256, 256, 3)


[574   1 319 908 904 315]
epoch: images_shape: gen_images.shape: = 641 (6, 256, 256, 3) (6, 256, 256, 3)
641 [D loss: 1.2887194156646729 | D Accuracy: 75.0] [G loss: 13.229171752929688]
[879 498 601 190 618 896]
epoch: images_shape: gen_images.shape: = 642 (6, 256, 256, 3) (6, 256, 256, 3)
642 [D loss: 0.780409574508667 | D Accuracy: 83.33333730697632] [G loss: 6.714790344238281]
[ 73 964 504 120 931 953]
epoch: images_shape: gen_images.shape: = 643 (6, 256, 256, 3) (6, 256, 256, 3)
643 [D loss: 1.9310739040374756 | D Accuracy: 83.33333134651184] [G loss: 8.177149772644043]
[697 380 711 848 150  26]
epoch: images_shape: gen_images.shape: = 644 (6, 256, 256, 3) (6, 256, 256, 3)
644 [D loss: 1.4607130289077759 | D Accuracy: 75.0] [G loss: 9.219717979431152]
[676 572 868 191 447 901]
epoch: images_shape: gen_images.shape: = 645 (6, 256, 256, 3) (6, 256, 256, 3)
645 [D loss: 0.8748325109481812 | D Accuracy: 75.0] [G loss: 4.451157093048096]
[194 817 332 598 950 524]
epoch: images_shape: ge

(25, 256, 256, 3)


[592 929 356 498 256 691]
epoch: images_shape: gen_images.shape: = 661 (6, 256, 256, 3) (6, 256, 256, 3)
661 [D loss: 0.6879152059555054 | D Accuracy: 83.33333730697632] [G loss: 9.074182510375977]
[667 721 646   3 699 136]
epoch: images_shape: gen_images.shape: = 662 (6, 256, 256, 3) (6, 256, 256, 3)
662 [D loss: 1.117472529411316 | D Accuracy: 91.66666269302368] [G loss: 4.504664421081543]
[251 477 198 534 330 799]
epoch: images_shape: gen_images.shape: = 663 (6, 256, 256, 3) (6, 256, 256, 3)
663 [D loss: 3.107248306274414 | D Accuracy: 41.66666865348816] [G loss: 1.5960761308670044]
[221 386 405 264 547 903]
epoch: images_shape: gen_images.shape: = 664 (6, 256, 256, 3) (6, 256, 256, 3)
664 [D loss: 0.5887521505355835 | D Accuracy: 83.33333134651184] [G loss: 2.932018995285034]
[907 823 864 747 563 230]
epoch: images_shape: gen_images.shape: = 665 (6, 256, 256, 3) (6, 256, 256, 3)
665 [D loss: 1.5300686359405518 | D Accuracy: 75.0] [G loss: 10.690705299377441]
[596 611 673 388 595 19

(25, 256, 256, 3)


[180 289 582 277 392 281]
epoch: images_shape: gen_images.shape: = 681 (6, 256, 256, 3) (6, 256, 256, 3)
681 [D loss: 0.36621081829071045 | D Accuracy: 83.33333134651184] [G loss: 8.801403045654297]
[564 198 935 509   7 300]
epoch: images_shape: gen_images.shape: = 682 (6, 256, 256, 3) (6, 256, 256, 3)
682 [D loss: 2.0457634925842285 | D Accuracy: 75.0] [G loss: 6.051755428314209]
[930 741 255 876 678 747]
epoch: images_shape: gen_images.shape: = 683 (6, 256, 256, 3) (6, 256, 256, 3)
683 [D loss: 0.36423590779304504 | D Accuracy: 83.33333730697632] [G loss: 6.555891513824463]
[517 508 452 424 710  72]
epoch: images_shape: gen_images.shape: = 684 (6, 256, 256, 3) (6, 256, 256, 3)
684 [D loss: 1.015965461730957 | D Accuracy: 83.33333730697632] [G loss: 11.41085147857666]
[355 142 556 793 331 218]
epoch: images_shape: gen_images.shape: = 685 (6, 256, 256, 3) (6, 256, 256, 3)
685 [D loss: 0.3144393265247345 | D Accuracy: 91.66666269302368] [G loss: 8.942835807800293]
[690 353 702 352 102  

(25, 256, 256, 3)


[458 196 503 638 926  54]
epoch: images_shape: gen_images.shape: = 701 (6, 256, 256, 3) (6, 256, 256, 3)
701 [D loss: 0.3173205554485321 | D Accuracy: 91.66666269302368] [G loss: 13.463793754577637]
[108  28 845 472 764 303]
epoch: images_shape: gen_images.shape: = 702 (6, 256, 256, 3) (6, 256, 256, 3)
702 [D loss: 0.6608316898345947 | D Accuracy: 83.33333730697632] [G loss: 5.904847621917725]
[484 414 645 552 413 313]
epoch: images_shape: gen_images.shape: = 703 (6, 256, 256, 3) (6, 256, 256, 3)
703 [D loss: 0.08444568514823914 | D Accuracy: 100.0] [G loss: 8.8123779296875]
[132 631 386 499 984 505]
epoch: images_shape: gen_images.shape: = 704 (6, 256, 256, 3) (6, 256, 256, 3)
704 [D loss: 0.9318692684173584 | D Accuracy: 75.0] [G loss: 5.963138580322266]
[330 112 974 359 587 460]
epoch: images_shape: gen_images.shape: = 705 (6, 256, 256, 3) (6, 256, 256, 3)
705 [D loss: 0.6411973834037781 | D Accuracy: 91.66666269302368] [G loss: 6.654073238372803]
[ 57 287 759 393 876 467]
epoch: im

(25, 256, 256, 3)


[325 816 124 732 658  23]
epoch: images_shape: gen_images.shape: = 721 (6, 256, 256, 3) (6, 256, 256, 3)
721 [D loss: 1.5497804880142212 | D Accuracy: 75.0] [G loss: 3.6965465545654297]
[539 386 434 590 639  50]
epoch: images_shape: gen_images.shape: = 722 (6, 256, 256, 3) (6, 256, 256, 3)
722 [D loss: 0.6302688717842102 | D Accuracy: 83.33333730697632] [G loss: 5.537242889404297]
[499 745 133  49 812  41]
epoch: images_shape: gen_images.shape: = 723 (6, 256, 256, 3) (6, 256, 256, 3)
723 [D loss: 2.41992449760437 | D Accuracy: 58.33333730697632] [G loss: 9.761425018310547]
[228 320 421 559 138 741]
epoch: images_shape: gen_images.shape: = 724 (6, 256, 256, 3) (6, 256, 256, 3)
724 [D loss: 2.255138874053955 | D Accuracy: 58.33333730697632] [G loss: 8.585269927978516]
[248 392 132 331 929 762]
epoch: images_shape: gen_images.shape: = 725 (6, 256, 256, 3) (6, 256, 256, 3)
725 [D loss: 0.5503103733062744 | D Accuracy: 83.33333134651184] [G loss: 6.772220134735107]
[817 331 764 228 205 746]

In [0]:
generate_imgs(25,(0.0, 0.1) , "")
